model:
  dim_treatments: 4
  dim_vitals: 0
  dim_static_features: 1
  dim_outcomes: 1
  autoregressive: true

  multi:  
    seq_hidden_units: 32
    br_size: 32
    fc_hidden_units: 64
    dropout_rate: 0.1
    num_heads: 2
    head_size: 8
    num_layer: 2
    attn_dropout: True
    disable_cross_attention: False
    isolate_subnetwork: False


dataset:
  val_batch_size: 64
  treatment_mode: multiclass

exp:
  seed: 42
  gpus: 0
  max_epochs: 10
  logging: False
  mlflow_uri: null
  unscale_rmse: True
  percentage_rmse: True

  alpha: 1.0
  update_alpha: True
  alpha_rate: exp
  balancing: grad_reverse

  bce_weight: False
  weights_ema: False
  beta: 0.99
